### ISSUE TITLE
Supplied Drush and Drupal 9.4

### ISSUE THREAD

**Issue by sonuku** [uselagoon/lagoon-images#488]
# Describe the bug

The Drush supplied at `/usr/local/bin/drush` seems to have issues with Drupal 9.4

After a fresh install, Running `/usr/local/bin/drush cex` produces an error. This strange interaction only seems to happen with the phar install. 

## To Reproduce

Steps to reproduce the behaviour:

1. Clone https://github.com/amazeeio/drupal-example-simple
2. `lando start`
3. `lando ssh`
4. `drush si -y`
5. Run `/app/vendor/bin/drush cex` a couple of times.

```
 [success] Configuration successfully exported to ../config/sync.
../config/sync
TYPO3\PharStreamWrapper\Exception: Unexpected file extension in "phar:///usr/local/bin/drush/.box/bin/core/modules/mysql/src/Driver/Database/mysql//Delete.php" in /app/web/core/lib/Drupal/Core/Security/PharExtensionInterceptor.php:44
Stack trace:
#0 /app/vendor/typo3/phar-stream-wrapper/src/Behavior.php(72): Drupal\Core\Security\PharExtensionInterceptor->assert('phar:///usr/loc...', 'url_stat')
#1 /app/vendor/typo3/phar-stream-wrapper/src/Manager.php(110): TYPO3\PharStreamWrapper\Behavior->assert('phar:///usr/loc...', 'url_stat')
#2 /app/vendor/typo3/phar-stream-wrapper/src/PharStreamWrapper.php(421): TYPO3\PharStreamWrapper\Manager->assert('phar:///usr/loc...', 'url_stat')
#3 /app/vendor/typo3/phar-stream-wrapper/src/PharStreamWrapper.php(410): TYPO3\PharStreamWrapper\PharStreamWrapper->assert('phar:///usr/loc...', 'url_stat')
#4 phar:///usr/local/bin/drush/.box/vendor/composer/ClassLoader.php(571): TYPO3\PharStreamWrapper\PharStreamWrapper->url_stat('phar:///usr/loc...', 2)
#5 phar:///usr/local/bin/drush/.box/vendor/composer/ClassLoader.php(571): include()
#6 phar:///usr/local/bin/drush/.box/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('core/modules/my...')
#7 [internal function]: Composer\Autoload\ClassLoader->loadClass('Drupal\\mysql\\Dr...')
#8 [internal function]: spl_autoload_call('Drupal\\mysql\\Dr...')
#9 /app/web/core/lib/Drupal/Core/Database/Connection.php(1129): class_exists('Drupal\\mysql\\Dr...')
#10 /app/web/core/lib/Drupal/Core/Database/Connection.php(1353): Drupal\Core\Database\Connection->getDriverClass('Delete')
#11 /app/web/core/lib/Drupal/Core/Lock/DatabaseLockBackend.php(168): Drupal\Core\Database\Connection->delete('semaphore')
#12 /app/web/core/includes/bootstrap.inc(734): Drupal\Core\Lock\DatabaseLockBackend->releaseAll()
#13 [internal function]: _drupal_shutdown_function()
#14 {main}
```

## Expected behaviour

Should export cex without issue.

It's mainly an issue when running `drush` commands via lagoon tasks. Theres other compounding errors that can occur with contrib such as `purge_processor_lateruntime`

## Additional context

I'm not sure where to direct this bug. Is it a drush bug?, is it a stack bug? Really hard to find the root issue. But it ONLY happens on the phar install. The composer install seems fine?! Affects drush 11 and 10.

As an interim workaround, I'm trialing running:
```
RUN rm -f /usr/local/bin/drush && ln -sf /app/vendor/bin/drush /usr/local/bin/drush
```

**Comment by sonuku** [comment]
https://www.drupal.org/project/drupal/issues/3291830

Seems relevant. Closing this issue.
